travis:
  secure:
    BINSTAR_TOKEN: bdIYCOjjgl1AkCqcAh8K3VIjEGXK4BiHMxlKa7fOa9Qjz9jc9lq/MxVFp5eDnrq24mTYnIwc8rLVOvel7t53FCXl3GJzo8+lpokH4l4gyyP4jZWebr5QNdVcDgPOvXESe1P4rR7ZYsBB/b/nPQfR+w0E8/8uJyrNvvIV35gPsvc4FMQvRmwf1WZqzXctzqs+xrRc6P8YSkQ9cVgPYHaXWCcn8NjcB0sIzG8mmScF2O/u5ZRvBMD+kwueSWu7On/snM8aZ9rIoooOpEjhkbk0APPJyFd2ypf5paZ97hlE7Cy8+uVfYAtMBMqrylO6UQs8cDQsAsnVqsQIi2Yo7fA6z+6LP8HzaWhpEv+niPrY/l/ea5mB0/ZX0Bu6o2jXFOGdNuCzSztM9ZuF/5ZsUuvFVEFlppoI2g+NfnjI/1C7kIcJXMqwlpDpvdc2s8vFusmw2KQhv4YQEqGngTsA+lhEm97g645AzalJ92fWLKfCfAtDGD23Cu2DH1QCr0Nk77RPsEJMcSQISet2WMeJaO+Wq9LDp4vrkNRqwCMSJcZkvBArYo3xf3+fVZ152buzuf7U5qVBoncHuxBrLZucAC7ZWwlZJXNePpOGl3jUWeliHjkqA9i6XyHDJbJ1JxbMeCc0pX7tkHoIRavue9fYxKAUzeKfx1TDMpK9EiMAA26KJz0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
