travis:
  secure:
    BINSTAR_TOKEN: BSW7EVlC0wxYiacKGmnSNUIRMHrp7rWEefg896jEU86etSIgyp0xYvv6+7XJ5cNcsHXF0RqZy6dB9T+dfkEHlPS0jn8UnpCh2SzwFK3Al8qFkUUt4eUo7p5U789Eos3EQsdM5Cy2MBiA9mauC+cKurhR0oiQenVUzBrIBQI6QW1UbBSOK3r5prRwDRNLyTSeUfp8O1gsAMTBNq3pay6MBhhgoX82CxoWoI8bUTBSrCBhBvuVy2G+n0T72pw7Hvum2pM1dlF5iZDSUbVGg2Pqj2KkciyIv3VSr7fa4nmoh/diWpkPdph8TkOHtg0TSqrXaBTvk4B2dZHqeJLIKsVi+XLZUuXzjKYgkfc2z5wwHB8a9dWP53IBXO0tphIhpprF2Ia9Zwqjmhfl8JqJ75pRFnz2H3xUjiXQeUeYa59z1fPFW7lhlfcqumAf/0t6LQLjL0GKvyvkpbKwUsrqNvMy0foo3W+mclujUvu9gj057tzPQHMx975EhRl/v0UQa2IHO9rSgyOhtFhFEP5a/vDOy2FVs4lxyOM4CTmOnuvxTBikXTpB04RnJyfb8ERTtL3dwbTmQow1TKr4yurFQHfU4kLfU2TBtrJtWFEkhucxusOMKiLsuCsGOYFvtX4+4ppCGo7zD6Net5DdkyKl4if6FkRsWAIC1sFmY2R4Bh5SZQ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
